server:
  port: 8080

spring:
  datasource:
    username: root
    password: TestSkillbox
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        default-character-set: utf8mb4
    hibernate:
      ddl-auto: update
    show-sql: true


indexing-settings:
  sites:
    - url: https://dombulgakova.ru
      name: Дом Булгакова
    - url: https://et-cetera.ru/mobile
      name: Et-Cetera
#    - url: https://www.playback.ru
#      name: PlayBack.Ru
#    - url: https://volochek.life
#      name: Волочек
#    - url: https://www.svetlovka.ru
#      name: Светловка
#    - url: https://www.lenta.ru
#      name: Лента.ру
